---
title: "CyberbullyingAnalysis"
format: html
editor: visual
---

## Setup

```{r setup}
#| message: false

library(tidyverse)
library(tidymodels)
library(tidytext)
library(plotly)

data <- read.csv("https://raw.githubusercontent.com/agmath/agmath.github.io/refs/heads/master/data/classification/cyberbullying_tweets.csv")

data |>
  count(cyberbullying_type) |>
  kbl()

data <- data |>
  distinct()

set.seed(19032025)

data_split <- initial_split(data, prop = 0.9)
train <- training(data_split)
test <- testing(data_split)
```

```{r head}
data |>
  head()
```

## Tokenization

```{r isolating words}
common_words_list <- train |>
  mutate(tweet_id = row_number()) |>
  unnest_tokens(word, tweet_text) |>
  anti_join(stop_words) |>
  filter(!(word %in% c("http", "https", "t.co", "bully", "bullies", "bullied"))) |>
  filter(!str_starts(word, "\\d+")) |>
  count(word) |>
  arrange(-n) |>
  filter(n >= 100) |>
  pull(word)


train |>
  mutate(tweet_id = row_number()) |>
  unnest_tokens(word, tweet_text) |>
  anti_join(stop_words) |>
  filter(!(word %in% c("http", "https", "t.co", "bully", "bullies", "bullied"))) |>
  filter(!str_starts(word, "\\d+")) |>
  filter(word %in% common_words_list) |>
  distinct() |> 
  slice(1:1e4) |> 
  mutate(
    present = 1
  ) |>
  pivot_wider(id_cols = c(cyberbullying_type, tweet_id),
              names_from = word,
              values_from = present)
```

## Data Viz

```{r}
train |>
  mutate(tweet_id = row_number()) |>
  unnest_tokens(word, tweet_text) |>
  anti_join(stop_words) |>
  filter(!(word %in% c("http", "https", "t.co", "bully", "bullies", "bullied"))) |>
  filter(!str_starts(word, "\\d+")) |>
  group_by(cyberbullying_type) |>
  count(word) |>
  top_n(15, n) |>
  ungroup() |>
  ggplot() +
  geom_bar(aes(x = reorder_within(word, n, cyberbullying_type), y = n, fill = cyberbullying_type),
           stat = "identity", color = "black",
           show.legend = FALSE) +
  scale_x_reordered() +
  facet_wrap(~cyberbullying_type, scales = "free_y") +
  coord_flip()
```

## Comparing Word Frequency Between Categories, Gender and Ethnicity

```{r}
p <- train |>
  filter((cyberbullying_type == "gender") | (cyberbullying_type == "ethnicity")) |>
  unnest_tokens(word, tweet_text) |>
  anti_join(stop_words) |>
  filter(!(word %in% c("http", "https", "t.co", "bully", "bullies", "bullied", "bullying"))) |>
  filter(!str_starts(word, "\\d+")) |>
  group_by(cyberbullying_type) |>
  count(word) |>
  filter(n > 25) |>
  pivot_wider(names_from = cyberbullying_type, values_from = n) |>
  ggplot() +
  geom_text(aes(x = ethnicity, y = gender, label = word)) +
  geom_abline(linetype = "dashed")

plotly::ggplotly(p)
```

## Regular Expressions

```{r}
train |>
  mutate(
    hashtags = str_extract_all(tweet_text, "#([A-z]|\\d|-|_)+")
  ) |>
  filter(lengths(hashtags) > 0) |>
  unnest(hashtags) |>
  mutate(
    mentions = str_extract(tweet_text, "@([A-z]|\\d|-|_)+")
  ) |>
  filter(!is.na(mentions))
```

