---
title: "Dimension Reduction PCA"
author: 
  -name: Vinny Chloros
  affiliations:
    -name: Southern New Hampshire University
date: 2/19/2025
date-modified: today
date-format: long
format: html
editor: visual
---

```{r setup}
library(tidyverse)
library(tidymodels)
library(ggforce)

data <- read_csv("https://raw.githubusercontent.com/agmath/agmath.github.io/master/data/classification/cancer_gene_expression_data.csv")

set.seed(5504)
gene_split <- initial_split(data, 0.80)

train <- training(gene_split)
test <- testing(gene_split)
```

```{r}
train %>%
  select(1:5, 2502) %>%
    ggplot(aes(x = .panel_x, y = .panel_y, color = labels, fill = labels)) +
    geom_point() +
    geom_autodensity(alpha = .3) +
    facet_matrix(vars(-labels), layer.diag = 2) + 
    scale_color_brewer(palette = "Dark2") + 
    scale_fill_brewer(palette = "Dark2")
```

```{r}
pca_rec <- recipe(labels ~ ., data = train) |>
  step_zv(all_predictors()) |>
  step_normalize(all_numeric_predictors()) |>
  step_pca(all_numeric_predictors())

pca_rec |>
  prep() |>
  tidy(number = 3, type = "variance") |>
  filter(terms == "percent variance") |>
  mutate(total_variance = cumsum(value))
```

```{r}
pca_rec <- recipe(labels ~ ., data = train) |>
  step_zv(all_predictors()) |>
  step_normalize(all_numeric_predictors()) |>
  step_pca(all_numeric_predictors(), num_comp = 5)


## shows the same output
pca_rec |>
  prep() |>
  tidy(number = 3, type = "variance") |>
  filter(terms == "percent variance") |>
  mutate(total_variance = cumsum(value))

train_baked <- pca_rec |>
  prep() |>
  bake(train)
```

```{r}
train_baked |>
  ggplot(aes(x = .panel_x, y = .panel_y, color = labels, fill = labels)) +
    geom_point() +
    geom_autodensity(alpha = .3) +
    facet_matrix(vars(-labels), layer.diag = 2) + 
    scale_color_brewer(palette = "Dark2") + 
    scale_fill_brewer(palette = "Dark2")
```

